# -*- coding: utf-8 -*-
"""CMPE255_AprioriAlgorithm_Amika.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vhw3y1rt16TjntEwV_vmDx4SuGhAwkZm
"""

#Installing apyori

pip install apyori

#Importing all the necessary libraries

import pandas as pd
import numpy as np
from apyori import apriori

#Loading and exploring the data

dataset = pd.read_csv('Movies.csv', encoding='latin1',header=None)

dataset

#Visualising the data

dataset.shape

dataset.replace([np.inf, -np.inf], np.nan, inplace=True)
# Drop rows with NaN
dataset.dropna(inplace=True)
print(dataset)

#Converting the pandas dataframe into a list of lists

records = []
for i in range(0,8211):
  records.append([str(dataset.values[i,j]) for j in range (0,14)])

#Building a apriori model

association_rules = apriori(records, min_support = 0.50, min_confidence= 0.5, min_lift=0.2,min_length=2)
association_results = list(association_rules)

#Getting the number of rules

print(len(association_results))

#Glancing at the first rule

print(association_results)

#Displaying all the association rules built by the model

association_results

#Building another association rule by updating the min_support value to 0.7

association_rules = apriori(records, min_support = 0.70, min_confidence= 0.5, min_lift=0.2,min_length=2)
association_results = list(association_rules)

#Displaying the 3 association rules built by the model

association_results

print(association_rules)

print(association_results)

